version = "0.1"

# Training data
# data_path = "./datafolder/dsgdb9nsd.xyz.tar"
data_path = "./datafolder/qm9.csv"
ckpt_path = ""

# Model HParams
num_atom = 20
num_atom_type = 8
num_bond_type = 4
num_hidden = 32
gen_layer = [128, 256, 512]

# Training HParams
batch_size = 256
learning_rate = 1e-3
nepoch = 100