version = "0.1"

# Training data
data_folder = "datafolder/dsgdb9nsd.xyz.tar.bz2"

# Model HParams
num_atom = 20
num_atom_type = 8
num_bond_type = 5
num_hidden = 32
gen_layer = [128, 256, 512]

# Training HParams
batch_size = 32

